export const newsSources = [
  {
    id: 1,
    name: "Tempo Bisnis",
    sub: "Tempo.co Berita Bisnis Terkini Indonesia dan Dunia RSS",
    url: "https://rss.tempo.co/bisnis",
    logo: "http://www.tilikfeed.com/logos/icons/tempo.png",
    news: [],
  },
  {
    id: 2,
    name: "Liputan 6",
    sub: "Liputan6.com Politik",
    url: "https://feed.liputan6.com/rss/news",
    logo: "http://www.tilikfeed.com/logos/icons/liputan6.jpeg",
    news: [],
  },
  {
    id: 3,
    name: "Tribunnews",
    sub: "Tribunnews.com",
    url: "https://www.tribunnews.com/rss",
    logo: "http://www.tilikfeed.com/logos/icons/tribunnews.png",
    news: [],
  },
  {
    id: 4,
    name: "CNBC Market",
    sub: "Market - Berita Terkini Market, Saham, Reksadana - CNBC Indonesia",
    url: "https://www.cnbcindonesia.com/market/rss/",
    logo: "http://www.tilikfeed.com/logos/icons/CNBC_Indonesia.png",
    news: [],
  },
  {
    id: 5,
    name: "Tempo Nasional",
    sub: "Tempo.co Berita Nasional Terbaru Indonesia Hari Ini RSS",
    url: "https://rss.tempo.co/nasional",
    logo: "http://www.tilikfeed.com/logos/icons/tempo.png",
    news: [],
  },
  {
    id: 6,
    name: "Republika",
    sub: "Republika Online RSS Feed",
    url: "https://www.republika.co.id/rss",
    logo: "http://www.tilikfeed.com/logos/icons/republika.png",
    news: [],
  },
  {
    id: 7,
    name: "Okezone",
    sub: "Sindikasi economy.okezone.com",
    url: "https://sindikasi.okezone.com/index.php/rss/0/RSS2.0",
    logo: "http://www.tilikfeed.com/logos/icons/okezone.png",
    news: [],
  },
  {
    id: 8,
    name: "Tirto",
    sub: "tirto.id",
    url: "https://tirto.id/sitemap/r/google-discover",
    logo: "http://www.tilikfeed.com/logos/icons/tirto.png",
    news: [],
  },
  {
    id: 9,
    name: "Detik News",
    sub: "Berita - Detikcom",
    url: "https://news.detik.com/berita/rss",
    logo: "http://www.tilikfeed.com/logos/icons/detik.png",
    news: [],
  },
  {
    id: 10,
    name: "Detik Finance",
    sub: "Finance - Detikcom",
    url: "https://finance.detik.com/rss",
    logo: "http://www.tilikfeed.com/logos/icons/detik.png",
    news: [],
  },
  {
    id: 11,
    name: "Viva",
    sub: "VIVA - Berita Harian Terkini, Terpopuler, Terbaru",
    url: "https://www.viva.co.id/get/all",
    logo: "http://www.tilikfeed.com/logos/icons/viva1.png",
    news: [],
  },
  {
    id: 12,
    name: "Kumparan",
    sub: "kumparan - #kumparanAdalahJawaban",
    url: "https://lapi.kumparan.com/v2.0/rss/",
    logo: "http://www.tilikfeed.com/logos/icons/kumparan2.png",
    news: [],
  },
  {
    id: 13,
    name: "Suara Pembaharuan",
    sub: "Suara Pembaharuan",
    url: "https://www.suarapembaharuan.com/feeds/posts/default",
    logo: "http://www.tilikfeed.com/logos/icons/suara-pembaharuan.png",
    news: [],
  },
  {
    id: 14,
    name: "SindoNews",
    sub: "Berita Terkini dan Informasi Terbaru Hari Ini - SINDOnews",
    url: "https://www.sindonews.com/feed",
    logo: "http://www.tilikfeed.com/logos/icons/sindonews1.png",
    news: [],
  },
  {
    id: 15,
    name: "CNBC News",
    sub: "News - Berita Terkini Indonesia dan Dunia - CNBC Indonesia",
    url: "https://www.cnbcindonesia.com/news/rss",
    logo: "http://www.tilikfeed.com/logos/icons/CNBC_Indonesia.png",
    news: [],
  },
  {
    id: 16,
    name: "CNN Nasional",
    sub: "CNN Indonesia | Berita Terkini Nasional",
    url: "https://www.cnnindonesia.com/nasional/rss",
    logo: "http://www.tilikfeed.com/logos/icons/CNN_Indonesia.png",
    news: [],
  },
  {
    id: 17,
    name: "CNN Ekonomi",
    sub: "CNN Indonesia | Berita Terkini Ekonomi",
    url: "https://www.cnnindonesia.com/ekonomi/rss",
    logo: "http://www.tilikfeed.com/logos/icons/CNN_Indonesia.png",
    news: [],
  },
  {
    id: 18,
    name: "Antara",
    sub: "Berita Top News - ANTARA News",
    url: "https://www.antaranews.com/rss/top-news",
    logo: "http://www.tilikfeed.com/logos/icons/antaranews2.png",
    news: [],
  },
];
